[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "info"

[target.thumbv7em-none-eabihf]
runner = ["probe-rs", "run", "--chip", "STM32F767ZITx", "--log-format", "{t} {L} {s}"]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
